language: nix
env:
    - NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz"
    - NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz"
script:
    - nix-build tests/intern.nix
    - nix-build tests/extern.nix

cache:
  directories:
      - /nix/store
  timeout: 1200
