language: nix
script:
    - git clone --depth 1 https://github.com/NixOS/nixpkgs ../nixpkgs
    - nix-build tests/intern.nix
    - nix-build tests/extern.nix

cache:
  directories:
      - /nix/store
